### ISSUE TITLE
Validation fails when charset is specified in Content-Type

### ISSUE THREAD

**Issue by nono3551** [Sibyx/django_api_forms#16]
When Content-Type: 'application/json' is sent in POST request, validation is successful. Problem is that library does not when charset is specified. 

Validation fails for Content-Type: 'application/json; charset=utf-8'.

https://tools.ietf.org/html/rfc2616#page-124
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

There is another directive **boundary** which may also beak library behavior.

**Comment by Sibyx** [comment]
Fixed in #17 release ad [0.13.0](https://pypi.org/project/django-api-forms/)
