### ISSUE TITLE
Key validation in DictionaryField

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/django_api_forms#21]
I think, it will be very nice to have possibility to define a form field for the dictionary key in [DictionaryField](https://github.com/Sibyx/django_api_forms/blob/master/django_api_forms/fields.py#L153).

**Comment by harlansgs** [comment]
What would constitute an invalid key?

**Comment by Sibyx** [comment]
@harlansgs Hi, I am thinking of possibility to do something like this:

**Example request**

```json
{
  "my_typed_dict": {
    "b061bb03-1eaa-47d0-948f-3ce1f15bf3bb": 2.718,
    "0a8912f0-6c10-4505-bc27-bbb099d2e395": 42
  }
}
```

**Example form**

```python
class AlbumForm(Form):
    my_typed_dict = DictionaryField(key_field=fields.UUIDFIeld(), value_field=fields.DateTimeField())
```

I am still undecided if it makes sense to have such a "feature". What do you think?

**Comment by bumblebee211196** [comment]
I would like to work on this issue.

**Comment by Sibyx** [comment]
@bumblebee211196 feel free to take the issue :) If you any questions don't hesitate to ask.

**Comment by bumblebee211196** [comment]
> @bumblebee211196 feel free to take the issue :) If you any questions don't hesitate to ask.

Sure!. Let me first collect a list of field types we can provide for the `keys` and `values` in the `DictionaryField`. We shall discuss on what to include and what not to include.

**Comment by Sibyx** [comment]
Hi @bumblebee211196, I think it is not necessary to specify allowed fields for dictionary `keys` and `values`. I am aware that not all fields are making sense as `keys`, but enforcing such limitations will be a needless complication. If we want to keep the codebase as simple and as fast as possible we can't do everything for the programmer (checking his logical errors). If you have a different opinion I am here to listen of course :)

**Comment by bumblebee211196** [comment]
Hey @Sibyx I am currently working on other priority work. I will visit this back once I am done with that.

**Comment by AmberAnsari89** [comment]
hi,
i am beginner in python/django..can you help to get a issue to solve at my level?

**Comment by Vrbitko** [comment]
Hello @Sibyx, is this issue still opened and free to take? Can i take it?

**Comment by Sibyx** [comment]
Hello @AmberAnsari89, feel free to take the issue. Basically all you need to know is stated in this issue so read it carefully. If you have any questions feel free to ask. Implementation is suppose to happen in the [DictionaryField](https://github.com/Sibyx/django_api_forms/blob/master/django_api_forms/fields.py#L179). Validation is executed in the `to_python` and you can mark validation error by raising `DetailValidationError` (if you have path to the key in a dictionary) or `ValidationError` if you have a generic error. Check existing implementation. Feel free to offer a PR so we can discuss the source code in the more practical way. Let me know if you are going to take the issue.

**Comment by AmberAnsari89** [comment]
thank you for your reply.. i ready to take the issue however i am new to open source area. so please help me with guidelines and source code and other details to do my analysis and get better insight.

**Comment by AmberAnsari89** [comment]
Hi,

I went through the issue and want more insight about the changes...what
exactly you want in place of dictionary field.i mean what structure of
formfiield..

**Comment by Sibyx** [comment]
You need to add new parameters to the `DictionaryField` constructor (check my [example in this issue](https://github.com/Sibyx/django_api_forms/issues/21#issuecomment-707384998)). Then in the `to_python` method you have to call validation (`to_python` methods for attributes from the constructor you created).
