### ISSUE TITLE
Raise ValidationError in invalid Data URI by default

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/django_api_forms#22]
From 1.0 ValidationError suppose to be raised if value of FileField and ImageField is not valid [Data URI](https://en.wikipedia.org/wiki/Data_URI_scheme).

**Comment by bumblebee211196** [comment]
Hi @Sibyx I would like to work on this issue!.

**Comment by Sibyx** [comment]
Hi @bumblebee211196, feel free to create a PR. Please keep in mind that exception have to be raised only if library version is `>= 1.0.0`. Major release is not ready yet, I am currently rewriting validation core with some breaking changes in `errors` property so your code should contain some kind of condition which will check version of the library.

**Comment by bumblebee211196** [comment]
Alright, will keep in mind the library version.
