### ISSUE TITLE
Property aliases

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/django_api_forms#27]
# Is your feature request related to a problem? Please describe.
Sometimes you need to have an ability to create mapping between `Form` properties and keys from request. 

For example, you want to map `_id`  JSON attribute into `id` property of `ExampleForm`.

```json
{
    "_id": 15
}
```

```python
class ExampleForm(Form):
     id = fields.IntegerField()
```

# Describe the solution you'd like
Introduce mapping property in `Form` object using Meta class.

```
class ExampleForm(Form):
    class Meta:
        # source:destination
        mapping = {
            '_id': 'id'
        }
     
     id = fields.IntegerField()
```

**Comment by DireWolf707** [comment]
Hye, I am new to open source but have experience working in django as you can see in my profile and want to contribute to this issue for hacktoberfest.
So, can you assign this issue to me?

**Comment by Sibyx** [comment]
Hi @DireWolf707,
sure feel free to solve this issue. Please keep in mind to use the Meta class as described. If you will have any questions feel free to ask.

**Comment by DireWolf707** [comment]
No luck :(
Sry for not informing
