### ISSUE TITLE
Empty FormFieldList validation

### ISSUE THREAD

**Issue by zurek11** [Sibyx/django_api_forms#32]
When I set FormFieldList required to true, empty list will raise an required exception.

I think that required validation should be assigned only to the key (if we think about json as a dictionary) and not to the value.

Maybe adding a new attribute `blank` or `empty` to the List type forms, to make control above values?

**Comment by TusharKuwar** [comment]
I would like to contribute to it, Please assign it to me

**Comment by Sibyx** [comment]
Hello @TusharKuwar, how are you doing? If you have any questions or need some help, feel free to ask

**Comment by TusharKuwar** [comment]
Hello @Sibyx , Thank you for contacting. 

So , I wanted to understand how field list are design. 
As far I was design, As far as I see, Error which we are talking about in this issue , written explicitly in test-cases. Its upto use case what to show. 

If I have wrong idea, or missing something, please let me know

**Comment by Sibyx** [comment]
Hi @TusharKuwar, problem described in this repository can by resolved by using `min_length` and `max_length` properties.
