### ISSUE TITLE
Linear validation errors

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/django_api_forms#35]
This issue has been inspired by [Problem Details for HTTP APIs - RFC7807](https://tools.ietf.org/html/rfc7807) and blog post [Structuring validation errors in REST APIs](https://medium.com/engineering-brainly/structuring-validation-errors-in-rest-apis-40c15fbb7bc3) written by @k3nn7.

The main idea is to simplify the validation process on the client-side by flattening errors output. To achieve such
a goal, the whole validation process have be rewritten (and luckily for us, much simplified). This will be a breaking change and will be released as 1.0.

The `DetailedValidationError` should be implemented which inherits from `ValidationError` and can keep position in lists nested forms. The form will return a linear list of errors instead of a nested dictionary.

**Example request**

```json
{
  "authors": [
    {
      "name": "Bla",
      "surname": "Bla"
    },
    {
      "surname": "Hihi"
    }
  ],
  "password": "password"
}
```

**Example validation error structure**

```json
{
  "errors": [
    {
      "path": ["authors", 1, "name"],
      "json-path": "$.authors.1.name",
      "message": "Field is required!",
      "code": "required"
    },
    {
      "path": ["password"],
      "json-path": "$.password",
      "message": "Password is too short!",
      "code": "too-short",
      "min-lenght": 10
    },
    {
      "path": ["password"],
      "json-path": "$.password",
      "message": "Password is too simple!",
      "code": "too-simple"
    },
    {
      "path": ["username"],
      "json_path": "$.username",
      "message": "Field have to be unique!",
      "code": "unique"
    }
  ]
}
```

**Comment by Serbel97** [comment]
Can you assign me?
