### ISSUE TITLE
Use `Poetry` for install, build and publish instead of `setuptools` and `twine`.

### ISSUE THREAD

**Issue by wiseaidev** [Sibyx/django_api_forms#43]
**Is your feature request related to a problem? Please describe.**

I have noticed that this project has an unnecessary `setup.py` file since it is already using poetry. Therefore, metadata that exists in `setup.py` should be moved into `pyproject.toml`.

**Describe the solution you'd like**

Given the above info, this requires changing some CIs like [publish.yml](https://github.com/Sibyx/django_api_forms/blob/master/.github/workflows/publish.yml) to use poetry based github actions like [publish-python-poetry-package](https://github.com/marketplace/actions/publish-python-poetry-package#example-workflow). Also, some commands to install, build and publish should be poetry based.

**Describe alternatives you've considered**
Not available.

**Additional context**
For security reasons, Pypi suggests using [API tokens](https://pypi.org/help/#apitoken) to authenticate instead of a username and password. That's pretty much it. What do you think? Also, I would like to work on this issue if possible.

**Comment by Sibyx** [comment]
Hello @wiseaidev, fine for me (I was supper lazy to update to PyPi API Tokens) so I am super happy about your contribution offer. Thank you very much.

**Comment by wiseaidev** [comment]
Hey @Sibyx, done. I think you forgot to add `Hacktoberfest` in the GitHub topics of the repo. I will take a look at other issues and see what I can contribute to. Have a nice day/night!
