### ISSUE TITLE
Updating Django Docs Links

### ISSUE THREAD

**Issue by kailashchoudhary11** [Sibyx/django_api_forms#46]
Many of the Links in the Readme File are pointing to Django Docs for the version < 3.2, which is no longer supported. I think these links should be updated to Django Version 3.2 atleast or higher than that.

**Comment by kailashchoudhary11** [comment]
If possible I would like to fix this!

**Comment by daaavo** [comment]
Hi is this issue still available I'd to give it a chance for the Hacktoberfest 😄
