### ISSUE TITLE
Add support for TypedDict

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/django_api_forms#62]
It would be nice to have something like TypedDictField around TypedDict structure.

**Comment by jairajsahgal** [comment]
I'll like to make a contribution here.

**Comment by Sibyx** [comment]
Hello @jairajsahgal ,

feel free to offer a PR. If you have any questions feel free to ask. It would be nice if you create a draft pull request with description of your solution proposal.

**Comment by LalegYoucef** [comment]
Hello @Sibyx , 

I will be working with @jairajsahgal  on the implementation of this feature. 

Regards,

**Comment by smitrami-123** [comment]
Hi @Sibyx If this issue is still not resolved, can you assign it to me?

**Comment by Sibyx** [comment]
@smitrami-123 sure, will you resolve it? It's open for a few years but everybody just wanted to assign it without any results. So I can assign it if you create a Draft PR so we can talk about implementation issues.
